import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <main className="overflow-y-hidden">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
